# Generated by Django 5.2 on 2026-01-17 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="セッション ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="進行中")),
            ],
            options={
                "verbose_name": "ゲームセッション",
                "verbose_name_plural": "ゲームセッション",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "ユーザー"),
                            ("assistant", "アシスタント"),
                            ("system", "システム"),
                        ],
                        max_length=10,
                        verbose_name="役割",
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="タイムスタンプ"),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="game.gamesession",
                        verbose_name="セッション",
                    ),
                ),
            ],
            options={
                "verbose_name": "チャットメッセージ",
                "verbose_name_plural": "チャットメッセージ",
                "ordering": ["timestamp"],
            },
        ),
    ]
